### ISSUE TITLE
Proxy error: Could not proxy request /question/1 from localhost:3000 to http://localhost:3001.

### ISSUE THREAD

**Issue by osvald-laurits** [sspringer82/quiz#3]
When I execute npm start I get the following error.

Proxy error: Could not proxy request /question/1 from localhost:3000 to http://localhost:3001.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

The browser displays the following page at http://localhost:3000 .

How can I fix this error?
![quiz](https://user-images.githubusercontent.com/14924571/63653608-7cc39300-c76f-11e9-9a91-09eebd6b1816.png)

**Comment by natschoman** [comment]
Start the backend with
`npm run backend`.
